api_version: gage/v1alpha1
kind: PipelineConfig
metadata:
  name: global_piqa_vllm_asynca
  description: using vllm_backend eval global_piqa

custom:
  steps:
    - step: inference
    - step: auto_eval

datasets:
  - dataset_id: global_piqa_ds
    hub: huggingface
    hub_params:
      hub_id: mrlbenchmarks/global-piqa-nonparallel
      split: test
      subset: 'eng_latn'
    loader: hf_hub
    params:
      preprocess: global_piqa_chat_preprocessor

backends:
  - backend_id: global_piqa_vllm_backend
    type: vllm
    config:
      model_path: /mnt/model/qwen2_5_05B
      tokenizer_path: /mnt/model/qwen2_5_05B
      force_tokenize_prompt: true
      tensor_parallel_size: 1
      max_tokens: 512
      sampling_params:
        temperature: 0.0
      max_batch_size: 1
      max_model_len: 512
      gpu_memory_utilization: 0.9
      async_max_concurrency: 8
      output_type: text
  - backend_id: global_piqa_litellm_backend
    type: litellm
    config:
      api_base: https://api.openai.com/v1
      model: gpt-4.1
      provider: openai
      generation_parameters:
        max_new_tokens: 512
        temperature: 0.0
      streaming: false
      max_retries: 6

role_adapters:
  - adapter_id: dut_global_piqa_vllm_qwen
    role_type: dut_model
    backend_id: global_piqa_litellm_backend
    #backend_id: global_piqa_vllm_backend
    capabilities:
      - chat_completion

metrics:
  - metric_id: global_piqa_accuracy_local
    implementation: global_piqa_accuracy_local

tasks:
  - task_id: global_piqa_eval
    dataset_id: global_piqa_ds
    max_samples: 10
    reporting:
      sinks:
        - type: console
        - type: file
          params:
            output_path: ${GAGE_EVAL_SAVE_DIR:-./runs}/global_piqa_vllm_events.jsonl
